### PR TITLE
Add Webpack 2.x dependency support

### LINKED ISSUE #125: please update webpack@2.x.x
i want use tree-shaking！

### PR DESCRIPTION
**Pull request by bisubus**
Fixes #125

### CODE REVIEW

**Comment by zwacky** [comment]
instead of altering the `dependency`, it should be done with `peerDependencies`:

```
"peerDependencies": {
    "webpack": "^2.1.0-beta || ^2.2.0-rc || ^2.0.0"
}
```

**Comment by zwacky** [comment]
the `"dependencies"` may stay with `"webpack": "^1.12.9"`, but it needs a new key `peerDependencies` with the mentioned values.

**Comment by bisubus** [comment]
@zwacky Wouldn't this propagate duplicate `webpack` packages if there will be different constraints in dependencies and peer dependencies? I don't see the reason why it shouldn't be done with `dependencies` alone. It looks like the plugin has no problems with Webpack 2.

Thanks for reminding on `2.2.0-rc` versions.

**Comment by TSMMark** [comment]
Can we please get 2.x.x support? It's been months.

**Comment by zwacky** [comment]
Hey @TSMMark, check out https://github.com/shama/webpack-stream/issues/125#issuecomment-258600779, with this I got it to work. cheers!

**Comment by shama** [comment]
Webpack has been updated to `^3.4.1`. Thanks!

**Pull request closed without merging**
