### PR TITLE
Webpack 5

### LINKED ISSUE #233: Error: Rule can only have one resource source when using webpack-stream
Hi,
I've recently encountered this very weird error after updating from webpack v4 to v5.

```sh
$ gulp build
[18:09:32] Using gulpfile ~/shared-drive-mover/gulpfile.js
[18:09:32] Starting 'build'...
[18:09:33] 'build' errored after 349 ms
[18:09:33] Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "exclude": {},
  "use": [
    {
      "loader": "ts-loader",
      "options": {
        "appendTsSuffixTo": [
          {}
        ]
      },
      "ident": "clonedRuleSet-1[0].rules[0]"
    }
  ]
}
    at checkResourceSource (/home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/RuleSet.js:167:11)
    at Function.normalizeRule (/home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/RuleSet.js:198:4)
    at /home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/RuleSet.js:110:20
    at Array.map (<anonymous>)
    at Function.normalizeRules (/home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/RuleSet.js:109:17)
    at new RuleSet (/home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/RuleSet.js:104:24)
    at new NormalModuleFactory (/home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/NormalModuleFactory.js:115:18)
    at Compiler.createNormalModuleFactory (/home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:636:31)
    at Compiler.newCompilationParams (/home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:653:30)
    at Compiler.compile (/home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:661:23)
    at /home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:529:11)
    at /home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:318:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/shared-drive-mover/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/user/shared-drive-mover/node_modules/tapable/lib/Hook.js:154:20)
    at /home/user/shared-drive-mover/node_modules/webpack-stream/node_modules/webpack/lib/Compiler.js:315:19
```

However, calling webpack directly works just fine:
```sh
$ webpack
asset index.js 21 bytes [compared for emit] [minimized] (name: index)
./index.ts 22 bytes [built] [code generated]
webpack 5.21.2 compiled successfully in 1406 ms
```

I've tried to clean up the repo and make it into a minimal repro, here it is: https://github.com/skaut/shared-drive-mover/tree/webpack-5-issue-repro

This issue only happens to me with webpack@v5, webpack-stream, vue and typescript. Removing any of these makes the issue disappear. I honestly don't know which package is the culprit but since there is a clear difference between using and not using this one, that'd be my most probable guess.

### PR DESCRIPTION
**Pull request by marekdedic**
Depends on #234. Should close #233

Please look at the changes, I only have a vague idea what I'm doing :D

### CODE REVIEW

**Comment by marekdedic** [comment]
I have tested this on my own package as well and it produces identical output to running webpack 5 directly.

**Comment by oFlo193o** [comment]
Hey, a merge would be highly appreciated. I've also tested your change and it also produced an identical output. 

I'm currently using a fork in our production app which i want to get rid of as soon as possible

**Comment by Ubernt** [comment]
Hey any updates on this? Merge would appreciated also!

**Comment by exinferis** [comment]
This is a real showstopper for me currently. Are there any updates on this regarding a possible merge / release?

**Comment by Ubernt** [comment]
Is there anyone who can do something about this PR? This has been waiting a bit long here and few developers wants this. I'd rather not fork branch and do it myself unless someone just merge this PR.

**Comment by internetchris** [comment]
PLEASE!!!!!! @shama

**Comment by marekdedic** [comment]
Guys, I'd like to see this merged as much as anyone, please keep it civil though...

This project is most likely volunteer-run, so there's no obligation or guarantee. If we don't want to wait, we can always fork and do the maintenance ourselves...

**Comment by TSMMark** [comment]
I've had to resort to using @marekdedic's fork in our package.json. Hopefully this gets merged and released soon, but at least we have this branch.

**Comment by Ubernt** [comment]
> I've had to resort to using @marekdedic's fork in our package.json. Hopefully this gets merged and released soon, but at least we have this branch.

Would you mind to comment here and let us know if the branch works perfectly, then I would do the same.

**Comment by TSMMark** [comment]
@Ubernt yep seems good to me. We've only been using webpack 5 in production for about a day, so not a huge sample size or anything... But so far so good for us at least.

This is the exact line in our package.json, in case anyone is not sure how to point to a git ref:

```
"webpack-stream": "github:marekdedic/webpack-stream#47609e89333a95fa699910e1ec04dc52ecd17096"
```

**Comment by CEbbinghaus** [comment]
Thank you @TSMMark that worked a treat. The fact that this has been open since the beginning of the year with no progress is a little frustrating since it solves such a basic and simple problem.

Hoping to see it ger merged soon 👍🏼

**Comment by Ubernt** [comment]
> @Ubernt yep seems good to me. We've only been using webpack 5 in production for about a day, so not a huge sample size or anything... But so far so good for us at least.
> 
> This is the exact line in our package.json, in case anyone is not sure how to point to a git ref:
> 
> ```
> "webpack-stream": "github:marekdedic/webpack-stream#47609e89333a95fa699910e1ec04dc52ecd17096"
> ```

I'm not sure did I do this correctly but using this git ref, npm install and then I checked from package.json in webpack-stream it is still pointing to 4.26.1.

**Comment by CEbbinghaus** [comment]
Thank you 👍🏼

**Comment by shama** [comment]
We should all beg the current webpack maintainers to support streaming in the native API and deprecate this library. Then y'all don't have to put up with the terrible maintainer of this project.

Thanks for the PR!

**Comment by alexander-akait** [comment]
Yep, make sense, PR welcome to webpack for streaming API

**Pull request merged**
